# locations.py

locations = {
    'Almere Duin': 'almere-duin',
    'Amsterdam Overhoeks': 'amsterdam-overhoeks',
    'Bennekom': 'bennekom',
    'Bergen op Zoom': 'bergen-op-zoom',
    'Deurne': 'deurne',
    'Dordrecht': 'dordrecht',
    'Druten': 'druten',
    'Emmen': 'emmen',
    'Etten-Leur': 'etten-leur',
    'Geldermalsen': 'geldermalsen',
    'Goes': 'goes',
    'Gorinchem': 'gorinchem',
    'Harderwijk': 'harderwijk',
    'Hoevelaken': 'hoevelaken',
    'Kerkdriel': 'kerkdriel',
    'Leusden': 'leusden',
    'Maastricht': 'maastricht',
    'Nijmegen': 'nijmegen',
    'Oosterbeek': 'oosterbeek',
    'Roden': 'roden',
    'Roermond': 'roermond',
    'Soesterberg': 'soesterberg',
    'Teteringen': 'teteringen',
    'Vleuten': 'vleuten',
    'Vlijmen': 'vlijmen',
    'Voorschoten': 'voorschoten',
    'Warmond': 'warmond',
    'Zwolle': 'zwolle',
    'Geen voorkeur': 'aanmelding'
}